name: STAN
# markdown: redcarpet
# markdown: kramdown
markdown: rdiscount
highlighter: pygments
# redcarpet:
  # extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables", "with_toc_data"]

exclude: ["pandoc", "reviews", "CONTRIBUTING.md", "README.md", "book", "extras"]
